# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220030e7e344c30296702675e7bec99451d5f7c57c801f12b06139b864ba319d604";
    path = fetchzip {
      url = "https://github.com/unicode-org/icu/archive/2d029329c82c7792b985024b2bdab5fc7278fbc8.tar.gz";
      hash = "sha256-0BxO5qd7u/rQ3wwC/u3PqO6XKThCB+srmangomc0Jng=";
    };
  }
]
